### ISSUE TITLE
无法使用 amsthm

### ISSUE THREAD

**Issue by tthigher** [qingbyin/swputhesis#3]
在导言区添加amsthm宏包后报错，内容为：
amsthm.sty error: Command \openbox already defined. 
请问怎么处理呢，无法添加定义、定理啥的，手动添加感觉不方便

**Comment by qingbyin** [comment]
和更改公式字体的包`{newtxmath}`冲突了。
快速解决办法，在`{amsthm}`之后加载字体修改：
* 打开 `swputhesis.cls` 找到 `\RequirePackage{newtxmath}` 这一行
* 在这一行前面加上一行 `\RequirePackage{amsthm}` 

```cls
\RequirePackage{amsthm}   % <--- 新添加
\RequirePackage{newtxmath}
```

**Comment by tthigher** [comment]
貌似添加子图的包也用不了，\usepackage{subfigure} 加载会报错
<img width="421" alt="image" src="https://user-images.githubusercontent.com/95599158/155893007-62703286-a074-42fc-8b0a-81ed69c26965.png">

**Comment by qingbyin** [comment]
`subfigure`包太老，已经停止维护了。应该用`subcaption`，功能是一样的。
以后如果有新问题麻烦创建新的issue。
